-- Execution Plan
-- It is a roadmap generated by a database on how it will execute the query step by step.

Select 
*
From FactResellerSales_HP

-- Estimated Execution Plan:  Predicts the execution plan without actually running the query.
-- Actual Execution Plan: Shows the execution plan as it ocurred after running the query.
-- Live Execution Plan: Shows the real-time execution flow as the query runs.
/*
Estimated Vs Actual Plans
- If the predictions don't match the atual execution plan, this indicates issues 
  like inaccurate statistics or outated indexes leading to poor performance.
*/

-- Table Scan: It reads the entire table, page by page and row by row which can lead to slower query performance on large datasets.
-- Index Scan: Scans all data in an index to find matching rows 

-- Heap Vs Clustered Index 
-- Heap Index
Select 
*
From FactResellerSales_HP
Order By SalesOrderNumber
-- Heap is much slower than clustered because the database must perform extra work to sort rows 

-- After creating a new index, check the execution plan to see if the query uses the index.

-- NonClustered Index
Select 
*
From FactResellerSales_HP
Where CarrierTrackingNumber = '4911-403C-98' 

/*
Types of Scan
1) Table Scan: Reads every row in a table. (Worst)
2) Index Scan: Reads all entries in an index to find results. (Intermediate)
3) Index Seek: Quickly locates specific rows in an index. (Best)
*/

/*
Joins Algorithms:
1) Nested Loops: Compares tables row by row; best for small tables.
2) Hash Match: Matches rows using a hash table; best for large tables.
3) Merge Join: Merge two sorted tables; efficient when both tables are sorted.
*/

-- Rowstore Vs Columnstore
Select 
p.EnglishProductName As ProductName,
Sum(s.SalesAmount) As TotalSales
From FactResellerSales_HP s
Join DimProduct p
On p.ProductKey = s.ProductKey
Group By p.EnglishProductName

Create Clustered Columnstore Index Idx_FactResellerSalesHp On FactResellerSales_Hp

-- Columnstore used way less CPU cost than Rowstore

-- SQL Hints: Commands that you add ta a query to force the database to run it in a specific way for better performance.
-- Use Forceseek or Hash Join one at a time or an error will occur
-- To use specific Joining type
Select
o.Sales,
c.Country
From Sales.Orders o
Left Join Sales.Customers c 
On o.CustomerID = c.CustomerID
Option (Hash Join)

-- To use specific index type
Select
o.Sales,
c.Country
From Sales.Orders o
Left Join Sales.Customers c  With (Forceseek)
On o.CustomerID = c.CustomerID

-- To target(use) a specific index
Select
o.Sales,
c.Country
From Sales.Orders o
Left Join Sales.Customers c  With (Index([PK_customers]))
On o.CustomerID = c.CustomerID

/*
Notes:
1) Test hints in all project environments (Dev, Prod) as performance may vary.
2) Hints are quick fixes (Workaround not a solution) and you still have to find the cause and fix the problem.
*/